namespace PdfConversion.Models;

/// <summary>
/// Represents a single item from the hierarchy XML structure
/// Used to define sections and their metadata for the conversion process
/// </summary>
public class HierarchyItem
{
    /// <summary>
    /// Unique identifier from @id attribute
    /// Example: "directors-report", "market-risk"
    /// </summary>
    public string Id { get; set; } = string.Empty;

    /// <summary>
    /// Hierarchical level from @level attribute
    /// Used for determining header hierarchy in output
    /// Example: 0 (root), 1 (main section), 2 (subsection)
    /// </summary>
    public int Level { get; set; }

    /// <summary>
    /// Output filename from @data-ref attribute
    /// Example: "directors-report.xml"
    /// </summary>
    public string DataRef { get; set; } = string.Empty;

    /// <summary>
    /// Display name from linkname element
    /// Used for matching against headers in source document
    /// Example: "Directors report", "Market risk"
    /// </summary>
    public string LinkName { get; set; } = string.Empty;

    /// <summary>
    /// Web page path from path element
    /// Example: "/", "/directors-report"
    /// </summary>
    public string WebPagePath { get; set; } = string.Empty;

    /// <summary>
    /// Path in web structure (alias for WebPagePath for consistency)
    /// </summary>
    public string Path
    {
        get => WebPagePath;
        set => WebPagePath = value;
    }

    /// <summary>
    /// Child items in the hierarchy
    /// </summary>
    public List<HierarchyItem> SubItems { get; set; } = new();

    /// <summary>
    /// Optional: AI confidence score (0-100) when generated by LLM
    /// </summary>
    public int? Confidence { get; set; }

    /// <summary>
    /// Optional: Whether this item was flagged as uncertain by AI
    /// </summary>
    public bool IsUncertain { get; set; }

    /// <summary>
    /// Optional: Whether this item was hallucinated (not found in source document)
    /// </summary>
    public bool IsHallucinated { get; set; }

    /// <summary>
    /// Optional: AI reasoning/explanation for this placement
    /// </summary>
    public string? Reasoning { get; set; }

    /// <summary>
    /// Optional: Marks the start of a TOC section (from data-tocstart attribute)
    /// </summary>
    public bool TocStart { get; set; }

    /// <summary>
    /// Optional: Marks the end of a TOC section (from data-tocend attribute)
    /// </summary>
    public bool TocEnd { get; set; }

    /// <summary>
    /// Optional: Section number in TOC (from data-tocnumber attribute)
    /// Examples: "1", "2.1", "4.6", "note 1"
    /// </summary>
    public string? TocNumber { get; set; }

    /// <summary>
    /// Optional: TOC numbering style (from data-tocstyle attribute)
    /// Examples: "default", "notes123"
    /// </summary>
    public string? TocStyle { get; set; }

    /// <summary>
    /// Optional: Hides item from table of contents (from data-tochide attribute)
    /// Used for utility pages like contact info that should exist but not appear in TOC
    /// </summary>
    public bool TocHide { get; set; }

    /// <summary>
    /// Optional: Data number from source document header (e.g., "1", "2.1", "4.6", "note 1")
    /// Used for hierarchy determination in Rule-Based Generator
    /// </summary>
    public string? DataNumber { get; set; }

    /// <summary>
    /// Optional: Header type from source document (H2, H3, H4, etc.)
    /// Used for display badges in Manual Mode
    /// </summary>
    public string? HeaderType { get; set; }

    /// <summary>
    /// Optional: Sequential order in source document (1, 2, 3...)
    /// Used for display badges in Manual Mode
    /// </summary>
    public int? SequentialOrder { get; set; }

    /// <summary>
    /// Controls whether this item's children are visible in the tree view
    /// Defaults to true (expanded) for better initial visibility
    /// </summary>
    public bool IsExpanded { get; set; } = true;

    // ==========================================
    // CONFIDENCE SCORING FIELDS (Rule-Based Generator)
    // ==========================================

    /// <summary>
    /// Confidence score for this hierarchy decision (0.0 = very uncertain, 1.0 = very confident).
    /// Calculated by Rule-Based Hierarchy Generator based on structural patterns.
    /// </summary>
    public double ConfidenceScore { get; set; } = 1.0;

    /// <summary>
    /// Flags indicating sources of uncertainty in this decision.
    /// Empty list means high confidence.
    /// </summary>
    public List<UncertaintyFlag> UncertaintyFlags { get; set; } = new();

    /// <summary>
    /// Context: Previous header at same level (for debugging/review).
    /// Null if this is the first item at this level.
    /// </summary>
    public string? PreviousHeader { get; set; }

    /// <summary>
    /// Context: Next header at same level (for debugging/review).
    /// Null if this is the last item at this level.
    /// </summary>
    public string? NextHeader { get; set; }

    /// <summary>
    /// Context: Approximate word count in content under this header.
    /// Used for confidence calculation (very short or very long content lowers confidence).
    /// </summary>
    public int WordCount { get; set; }

    /// <summary>
    /// Context: Number of immediate child headers under this header.
    /// Used for confidence calculation (structure indicator).
    /// </summary>
    public int ChildCount { get; set; }

    /// <summary>
    /// Line number in the original input document (1-based).
    /// Used for document order validation - parent must appear BEFORE child.
    /// </summary>
    public int LineNumber { get; set; }

    /// <summary>
    /// Returns a formatted string for logging and debugging
    /// </summary>
    public override string ToString() => $"{LinkName} (Level {Level}, ID: {Id}, Confidence: {ConfidenceScore:F2})";
}
