using System.Text.Json;
using Microsoft.Extensions.Logging;
using Moq;
using PdfConversion.Models;
using PdfConversion.Services;
using Xunit;

namespace PdfConversion.Tests.Services;

/// <summary>
/// Integration tests for ProjectLabelService
/// Tests filesystem scanning, JSON persistence, and display string generation
/// </summary>
public class ProjectLabelServiceTests : IDisposable
{
    private readonly string _testDataPath;
    private readonly string _testLabelsFile;
    private readonly ProjectLabelService _service;
    private readonly Mock<ILogger<ProjectLabelService>> _mockLogger;

    public ProjectLabelServiceTests()
    {
        // Create unique temp directory for each test run
        _testDataPath = Path.Combine(Path.GetTempPath(), $"test-labels-{Guid.NewGuid()}");
        _testLabelsFile = Path.Combine(_testDataPath, "project-labels.json");

        Directory.CreateDirectory(_testDataPath);

        // Create service with test-specific labels file path
        _mockLogger = new Mock<ILogger<ProjectLabelService>>();
        _service = new ProjectLabelService(_mockLogger.Object);

        // Use reflection to set the private _labelsFilePath field for testing
        var field = typeof(ProjectLabelService).GetField("_labelsFilePath",
            System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance);
        field?.SetValue(_service, _testLabelsFile);
    }

    public void Dispose()
    {
        // Clean up test data
        if (Directory.Exists(_testDataPath))
        {
            Directory.Delete(_testDataPath, recursive: true);
        }
    }

    [Fact]
    public async Task GetAllProjects_ShouldDiscoverAllCustomerProjects()
    {
        // Arrange - Create test directory structure
        var customer1 = Path.Combine(_testDataPath, "customer1", "projects");
        var customer2 = Path.Combine(_testDataPath, "customer2", "projects");

        Directory.CreateDirectory(Path.Combine(customer1, "ar24-1"));
        Directory.CreateDirectory(Path.Combine(customer1, "ar24-2"));
        Directory.CreateDirectory(Path.Combine(customer2, "ar24-3"));

        // Act
        var projects = await _service.GetAllProjectsAsync(_testDataPath);

        // Assert
        Assert.Equal(3, projects.Count);
        Assert.Equal(2, projects.Count(p => p.Customer == "customer1"));
        Assert.Single(projects.Where(p => p.Customer == "customer2"));
        Assert.Contains(projects, p => p.ProjectId == "ar24-1");
        Assert.Contains(projects, p => p.ProjectId == "ar24-2");
        Assert.Contains(projects, p => p.ProjectId == "ar24-3");
    }

    [Fact]
    public async Task SetProjectLabel_ShouldPersistToJson()
    {
        // Arrange
        var customer = "testcustomer";
        var projectId = "ar24-1";
        var label = "Test Annual Report 2024";

        // Act
        await _service.SetProjectLabelAsync(customer, projectId, label);

        // Assert - Verify file was created
        Assert.True(File.Exists(_testLabelsFile));

        // Assert - Verify JSON content
        var json = await File.ReadAllTextAsync(_testLabelsFile);
        var data = JsonSerializer.Deserialize<ProjectLabelsData>(json,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

        Assert.NotNull(data);
        Assert.NotNull(data.Projects);
        Assert.True(data.Projects.ContainsKey(customer));
        Assert.True(data.Projects[customer].ContainsKey(projectId));
        Assert.Equal(label, data.Projects[customer][projectId].Label);
        Assert.True(data.LastModified > DateTime.UtcNow.AddMinutes(-1));
    }

    [Fact]
    public async Task GetDisplayString_WithCustomLabel_ReturnsFormattedString()
    {
        // Arrange
        var customer = "optiver";
        var projectId = "ar24-3";
        var customLabel = "Annual Report 2024 (Consolidated)";

        await _service.SetProjectLabelAsync(customer, projectId, customLabel);

        // Act
        var displayString = await _service.GetDisplayStringAsync(customer, projectId);

        // Assert
        var expected = $"{customLabel} ({projectId})";
        Assert.Equal(expected, displayString);
    }

    [Fact]
    public async Task GetDisplayString_WithoutLabel_ReturnsAutoGenerated()
    {
        // Arrange
        var customer = "optiver";
        var projectId = "ar24-3";

        // Act - No label set, should use fallback
        var displayString = await _service.GetDisplayStringAsync(customer, projectId);

        // Assert - Should generate fallback: "Annual Report 2024 (3) (ar24-3)"
        Assert.Equal("Annual Report 2024 (3) (ar24-3)", displayString);
    }

    [Fact]
    public async Task GetDisplayString_NonStandardId_ReturnsConsistentFormat()
    {
        // Arrange
        var customer = "testcustomer";
        var projectId = "xyz-123";

        // Act - Non-standard ID should use ID as label
        var displayString = await _service.GetDisplayStringAsync(customer, projectId);

        // Assert - Format: "{projectId} ({projectId})"
        Assert.Equal("xyz-123 (xyz-123)", displayString);
    }

    [Fact]
    public async Task DeleteProjectLabel_ShouldRemoveFromJson()
    {
        // Arrange
        var customer = "testcustomer";
        var projectId = "ar24-1";
        var label = "Test Label";

        await _service.SetProjectLabelAsync(customer, projectId, label);

        // Act
        await _service.DeleteProjectLabelAsync(customer, projectId);

        // Assert - Verify label was removed
        var retrievedLabel = await _service.GetProjectLabelAsync(customer, projectId);
        Assert.Null(retrievedLabel);

        // Assert - Verify JSON was updated
        var json = await File.ReadAllTextAsync(_testLabelsFile);
        var data = JsonSerializer.Deserialize<ProjectLabelsData>(json,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

        Assert.NotNull(data);
        Assert.NotNull(data.Projects);
        Assert.True(data.Projects.ContainsKey(customer));
        Assert.False(data.Projects[customer].ContainsKey(projectId));
    }

    [Fact]
    public async Task GetDisplayString_ArPatternFallback_GeneratesCorrectYear()
    {
        // Arrange
        var customer = "testcustomer";

        var testCases = new[]
        {
            ("ar24-1", "Annual Report 2024 (1) (ar24-1)"),
            ("ar23-5", "Annual Report 2023 (5) (ar23-5)"),
            ("ar25-10", "Annual Report 2025 (10) (ar25-10)")
        };

        foreach (var (projectId, expectedDisplay) in testCases)
        {
            // Act
            var displayString = await _service.GetDisplayStringAsync(customer, projectId);

            // Assert
            Assert.Equal(expectedDisplay, displayString);
        }
    }

    [Fact]
    public async Task GetProjectLabel_ReturnsNullWhenNotFound()
    {
        // Arrange
        var customer = "nonexistent";
        var projectId = "ar24-1";

        // Act
        var label = await _service.GetProjectLabelAsync(customer, projectId);

        // Assert
        Assert.Null(label);
    }

    [Fact]
    public async Task SetProjectLabel_CreatesFileIfNotExists()
    {
        // Arrange
        Assert.False(File.Exists(_testLabelsFile));

        var customer = "testcustomer";
        var projectId = "ar24-1";
        var label = "First Label";

        // Act
        await _service.SetProjectLabelAsync(customer, projectId, label);

        // Assert
        Assert.True(File.Exists(_testLabelsFile));

        var retrievedLabel = await _service.GetProjectLabelAsync(customer, projectId);
        Assert.Equal(label, retrievedLabel);
    }

    [Fact]
    public async Task SetProjectLabel_HandlesMultipleCustomers()
    {
        // Arrange
        var customers = new[] { "customer1", "customer2", "customer3" };
        var projectIds = new[] { "ar24-1", "ar24-2", "ar24-3" };

        // Act - Set labels for multiple customers
        for (int i = 0; i < customers.Length; i++)
        {
            await _service.SetProjectLabelAsync(customers[i], projectIds[i], $"Label {i + 1}");
        }

        // Assert - Verify all labels are persisted correctly
        for (int i = 0; i < customers.Length; i++)
        {
            var label = await _service.GetProjectLabelAsync(customers[i], projectIds[i]);
            Assert.Equal($"Label {i + 1}", label);
        }

        // Assert - Verify JSON structure
        var json = await File.ReadAllTextAsync(_testLabelsFile);
        var data = JsonSerializer.Deserialize<ProjectLabelsData>(json,
            new JsonSerializerOptions { PropertyNameCaseInsensitive = true });

        Assert.NotNull(data);
        Assert.NotNull(data.Projects);
        Assert.Equal(3, data.Projects.Count);
        foreach (var customer in customers)
        {
            Assert.True(data.Projects.ContainsKey(customer));
        }
    }

    [Fact]
    public async Task GetAllProjects_WithLabels_ReturnsCorrectDisplayStrings()
    {
        // Arrange - Create projects with custom labels
        var customer = "testcustomer";
        var projectsPath = Path.Combine(_testDataPath, customer, "projects");

        Directory.CreateDirectory(Path.Combine(projectsPath, "ar24-1"));
        Directory.CreateDirectory(Path.Combine(projectsPath, "ar24-2"));
        Directory.CreateDirectory(Path.Combine(projectsPath, "xyz-123"));

        // Set custom label for ar24-1
        await _service.SetProjectLabelAsync(customer, "ar24-1", "Custom Label One");

        // Act
        var projects = await _service.GetAllProjectsAsync(_testDataPath);

        // Assert
        var project1 = projects.First(p => p.ProjectId == "ar24-1");
        var project2 = projects.First(p => p.ProjectId == "ar24-2");
        var project3 = projects.First(p => p.ProjectId == "xyz-123");

        Assert.Equal("Custom Label One (ar24-1)", project1.DisplayString);
        Assert.Equal("Annual Report 2024 (2) (ar24-2)", project2.DisplayString);
        Assert.Equal("xyz-123 (xyz-123)", project3.DisplayString);

        Assert.Equal("Custom Label One", project1.CustomLabel);
        Assert.Null(project2.CustomLabel);
        Assert.Null(project3.CustomLabel);
    }
}
